<a href="https://colab.research.google.com/github/chewzzz1014/DPhi-Bootcamp/blob/master/notes/deep-learning/Tensorflow_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basics Properties of Tensor and Some Operations (Reshape, Squeeze, Flatten, Concat)

In [2]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.8.2


Rank of tensor:
 - Rank 0 : Scalar (Single Number)
 - Rank 1 : Vector (Array)
 - Rank 2 : Matrix (2-D Array)
 - Rank n>2 : Tensor (n-dimensional Array)

# Dimension, Indexes, Rank, Axes and Shape

In [ ]:
# Dimension : Similar to dimension of object (length, width, depth) in real life

In [8]:
# Indexes : To access an element in data structure
list = [2, 4, 6, 8]
print("Third Element : {}".format(list[2]))

ll = [
      [1, 3, 5, 7, 9],
      [2, 4, 6, 8, 10],
      [-1, -2, -3, -4, -5]
]
print("Third element in first row : {}".format(ll[0][2]))

Third Element : 6
Third element in first row : 5


In [9]:
# Rank : Number of dimensions present within the tensor
# indicates the number of indexes needed to refer to an element

# rank 2 (2-D Array) needs 2 indexes to refer an element
ll[0]  # first axis [1, 3, 5, 7, 9]
ll[1][2]  # second axis, 6

6

In [10]:
# shape : Length of each axis. Given the shape of tensor, we will know the length of each axis

t = tf.constant(ll) # create a constant tensor
t

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [-1, -2, -3, -4, -5]], dtype=int32)>

In [11]:
type(t)

tensorflow.python.framework.ops.EagerTensor

In [12]:
# get the shape of a tensor
t.shape

TensorShape([3, 5])

# Tensor Operations

reshape
 - For tensor of x elements, only allowed to reshaped into shape (m, n)such that m * n = x

In [14]:
# reshape tensor without changing the rank
t1 = tf.constant([
      [1, 1, 1, 1],
      [2, 2, 2, 2],
      [3, 3, 3, 3]
], dtype = tf.float32)

In [26]:
# tf.reshape() will reshape any n-dimension array or n-dimension tensor 
t1_reshaped = tf.reshape(t1, [1,12]) # reshape into shape [1, 12]
print(t1_reshaped)
print(t1.shape) # did not reshape tensor in place

tf.Tensor([[1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.]], shape=(1, 12), dtype=float32)
(3, 4)


In [27]:
t1_reshaped = tf.reshape(t1, [2, 6]) # reshape into shape [2, 6]
print(t1_reshaped)
print(t1.shape) # did not reshape tensor in place

tf.Tensor(
[[1. 1. 1. 1. 2. 2.]
 [2. 2. 3. 3. 3. 3.]], shape=(2, 6), dtype=float32)
(3, 4)


In [28]:
t1_reshaped = tf.reshape(t1, [3, 4]) # reshape into shape [3, 4]
print(t1_reshaped)
print(t1.shape) # did not reshape tensor in place

tf.Tensor(
[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]], shape=(3, 4), dtype=float32)
(3, 4)


Squeezing and Unsqueezing (Changing Shape)
 - Squeezing : Remove the dimensions or axes with length of 1
 - Unsqueezing : Add a dimension with length of 1

In [25]:
print(tf.reshape(t1, [1, 12]) )

tf.Tensor([[1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.]], shape=(1, 12), dtype=float32)


In [29]:
print(tf.squeeze(tf.reshape(t1, [1, 12])))
print(tf.squeeze(tf.reshape(t1, [1, 12])).shape)

tf.Tensor([1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.], shape=(12,), dtype=float32)
(12,)


Flatten 
 - Reshape tensor to have shape equal to number of elements in tensor
 - Same as 1-d array 

In [30]:
def flatten(t):
  t = tf.reshape(t, [1, -1])  
# -1 mean tf.reshape() will figure out what the value should be based on num of elements
  t = tf.squeeze(t)
  return t

In [31]:
# create a tensor with all elements have the value 1
t2 = tf.ones([4, 3])
t2

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [32]:
# flatten the tensor
flatten(t2)

<tf.Tensor: shape=(12,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

Concatenating Tensors
 - Resulting tensor will have shape depends on shape of 2 input tensors

In [33]:
# concatenate 2 tensors
t3 = tf.constant([
    [1, 2],
    [3, 4]
])

t4 = tf.constant([
    [5, 6], 
    [7, 8]
])

In [35]:
# axis : 0 indicates row-wise and 1 indicates column-wise
tf.concat( (t3, t4), axis = 0)  # row-wise : concat t4 to rows of t3

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [37]:
# axis : 0 indicates row-wise and 1 indicates column-wise
tf.concat( (t3, t4), axis = 1)  # column-wise : concat t4 to columns of t3

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 5, 6],
       [3, 4, 7, 8]], dtype=int32)>

In [38]:
print( tf.concat( (t3, t4), axis = 0).shape )
print( tf.concat( (t3, t4), axis = 1).shape )

(4, 2)
(2, 4)
