<a href="https://colab.research.google.com/github/chewzzz1014/DPhi-Bootcamp/blob/master/notes/deep-learning/Tensorflow_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

# Basics

In [4]:
# creating tensor of rank 0-n

# rank 0 tensor
rank_0 = tf.constant(10)
print(rank_0)

# rank 1 tensor
rank_1 = tf.constant([2, 4, 6, 8])
print(rank_1)

# rank 2 tensor
rank_2 = tf.constant([
    [5, 6],
    [7, 8]
])
print(rank_2)

# rank 3 tensor
rank_3 = tf.constant([
      [[0, 1, 2, 3, 4],
      [5, 6, 7, 8, 9]],
      [[10, 11, 12, 13, 14],
      [15, 16, 17, 18, 19]],
      [[20, 21, 22, 23, 24],
      [25, 26, 27, 28, 29]],])

print(rank_3)

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor([2 4 6 8], shape=(4,), dtype=int32)
tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [13]:
# create a rank 4 tensor
rank_4 = tf.zeros([3, 5, 2, 3])

# data type
print("Type: {}".format(rank_4.dtype))
# num of dimension
print("Num of Dimension: {}".format(rank_4.ndim))
# shape
print("Shape: {}".format(rank_4.shape))
# Shape of First Axis
print("Size of first axis: {}".format(rank_4.shape[0]))
# shape of Last Axis
print("Size of Last Axis: {}".format(rank_4.shape[-1]))
# total number of elements
print("NUmber of elements: {}".format( tf.size(rank_4).numpy() ))

Type: <dtype: 'float32'>
Num of Dimension: 4
Shape: (3, 5, 2, 3)
Size of first axis: 3
Size of Last Axis: 3
NUmber of elements: 90


# Tensor -> Numpy Array

In [5]:
# using np.array
np.array(rank_2)

array([[5, 6],
       [7, 8]], dtype=int32)

In [6]:
# using tensor.numpy()
rank_2.numpy()

array([[5, 6],
       [7, 8]], dtype=int32)

# Indexing 

In [15]:
# slicing (similar to slicing in python and numpy)
print(rank_2[:2].numpy())
print(rank_3[:, :, 4])

[[5 6]
 [7 8]]
tf.Tensor(
[[ 4  9]
 [14 19]
 [24 29]], shape=(3, 2), dtype=int32)


# Maths on Tensor

In [10]:
# addition, element-wise multiplication and matrix-wise multiplication
a = tf.constant([
    [1, 2],
    [3, 4]
])

b= tf.constant([
    [5, 6],
    [7, 8]
])

print("Addition: {}".format(tf.add(a,b))) # or a + b
print("Element-wise Mul: {}".format(tf.multiply(a,b)))  # or a * b
print("Matirx Mul: {}".format(tf.matmul(a,b)))  # or a @ b

Addition: [[ 6  8]
 [10 12]]
Element-wise Mul: [[ 5 12]
 [21 32]]
Matirx Mul: [[19 22]
 [43 50]]


# DTypes
  - Integer : tf.int32
  - Floating Point : tf.float32

In [20]:
# cast type
f64_tensor = tf.constant([2.5, 3.3, 5.6], dtype=tf.float64)

f16_tensor = tf.cast(f64_tensor, dtype=tf.float16)

# decimal to integer
u8_tensor = tf.cast(f16_tensor, dtype=tf.uint8)
print(u8_tensor)

tf.Tensor([2 3 5], shape=(3,), dtype=uint8)
